app:
  data_dir: "data"
  db_path: "data/ohlcv.db"     # SQLite na start; łatwo zamienić na Postgres/Timescale
  timezone: "UTC"

exchange:
  id: "bitget"                 # możesz zmienić np. na "binance"
  rate_limit_ms: 350

symbols:
  - "BTC/USDT:USDT"
  - "ETH/USDT:USDT"
  - "SOL/USDT:USDT"
  - "XRP/USDT:USDT"
  - "DOGE/USDT:USDT"
  - "ADA/USDT:USDT"
  - "AVAX/USDT:USDT"
  - "LINK/USDT:USDT"
  - "TON/USDT:USDT"
  - "PEPE/USDT:USDT"

timeframes:
  - "1m"        # baza (z niej zrobisz lokalny resampling)
  - "5m"
  - "15m"
  - "1h"

backfill:
  start_days_ago: 365          # ile wstecz pobrać przy pierwszym uruchomieniu
  batch_limit: 1000            # ile świec na jedno zapytanie (dopasuj do giełdy)

incremental:
  overlap_candles: 1           # ile świec nakładać na pobór (idempotencja)
  run_seconds: 60              # co ile sekund odpalać przyrosty (1m dla TF=1m)
