app:
  data_dir: "data"
  db_path: "data/ohlcv.db"
  timezone: "UTC"

exchange:
  id: "bitget"
  rate_limit_ms: 350

symbols:
  - "BTC/USDT:USDT"
  - "ETH/USDT:USDT"
  - "SOL/USDT:USDT"
  - "XRP/USDT:USDT"
  - "DOGE/USDT:USDT"
  - "ADA/USDT:USDT"
  - "AVAX/USDT:USDT"
  - "LINK/USDT:USDT"
  - "TON/USDT:USDT"
  - "PEPE/USDT:USDT"

timeframes:
  - "1m"
  - "5m"
  - "15m"
  - "1h"

data:
  base_timeframe: "1m"
  derived_timeframes: ["5m", "15m", "1h"]
  resample:
    run_seconds: 60
    lookback_minutes: 720

backfill:
  start_date: "2020-01-01"
  start_days_ago: 365
  batch_limit: 1000

incremental:
  overlap_candles: 1
  run_seconds: 60

signals:
  scan_seconds: 60
  lookback_candles: 300
  atr_period: 14
  atr_mult_sl: 1.5
  fibo:
    use: true
    piv_window: 5
    anchors_to_consider: 3
  avwap:
    use: true
  min_tp_net_pct: 2.0
  fees:
    taker_pct: 0.06
    maker_pct: 0.02
    assume_maker: false
  slippage_pct: 0.02
  validity_candles: 60
  bar_policy: "conservative"
  evaluation:
    usd_per_trade: 100

risk:
  mode: "normal"
  risk_pct_by_mode:
    conservative: 0.25
    normal: 0.50
    aggressive: 1.00
  max_leverage: 10.0
  liquidation_buffer: 0.50

execution:
  tp1_fraction: 0.5
  move_sl_to_be_on_tp1: true
  trail:
    use: true
    method: "atr"
    atr_period: 14
    atr_mult: 1.0

models:
  meta:
    enabled: true
    model_path: "models/meta_xgb.pkl"
    threshold: 0.60
    lookback_candles: 300
    min_signals_for_training: 200
    calibration:
      enabled: true
      path: "models/meta_cal.pkl"
    gating:
      use_ev: true
      min_ev_pct: 0.00
      costs_mode: "auto"
      target_winrate_pct: 60.0
      min_closed_samples: 60
      window_days: 120
      per_pair_tf: {}
      # NOWE: progi per reżim rynku (nadpisują globalne; łączą się z per_pair_tf)
      per_regime:
        trend:
          min_ev_pct: 0.20
          threshold: 0.70
        range:
          min_ev_pct: 0.00
          threshold: 0.60
        vol_high:
          min_ev_pct: 0.30
        vol_low:
          min_ev_pct: 0.00

auto:
  enabled: true
  weekly_train:
    enable: true
    day_of_week: "sun"
    hour_utc: 21
    minute: 0
  weekly_calibrate:
    enable: true
    day_of_week: "sun"
    hour_utc: 21
    minute: 30
  weekly_tune:
    enable: true
    mode: "ev"
    window_days: 120
    day_of_week: "sun"
    hour_utc: 22
    minute: 0

notify:
  telegram:
    enabled: false        # ustaw na true po wklejeniu tokenu/chat_id
    bot_token: ""
    chat_id: ""
    send_on:
      new_signal: true
      closed_trade: true
    throttle_seconds: 2
