app:
  data_dir: "data"
  db_path: "data/ohlcv.db"
  timezone: "UTC"

exchange:
  id: "bitget"          # zmień np. na "binance", "bitstamp" itp.
  rate_limit_ms: 350

symbols:
  - "BTC/USDT:USDT"
  - "ETH/USDT:USDT"
  - "SOL/USDT:USDT"
  - "XRP/USDT:USDT"
  - "DOGE/USDT:USDT"
  - "ADA/USDT:USDT"
  - "AVAX/USDT:USDT"
  - "LINK/USDT:USDT"
  - "TON/USDT:USDT"
  - "PEPE/USDT:USDT"

# Timeframe’y, które chcesz mieć dostępne w bazie (1m jest bazą)
timeframes:
  - "1m"
  - "5m"
  - "15m"
  - "1h"

# Dane: tylko 1m pobieramy z giełdy; wyższe TF liczymy lokalnie (resampling)
data:
  base_timeframe: "1m"
  derived_timeframes: ["5m", "15m", "1h"]
  resample:
    run_seconds: 60
    lookback_minutes: 720

backfill:
  # Używane przy pierwszym pobraniu archiwum.
  # Jeśli podasz start_date (YYYY-MM-DD), ma PRIORYTET nad start_days_ago.
  start_date: "2020-01-01"    # początek historii (np. do BTC na spocie); dla perpów ustaw realny start
  start_days_ago: 365         # fallback, jeśli start_date jest puste
  batch_limit: 1000

incremental:
  overlap_candles: 1
  run_seconds: 60

signals:
  scan_seconds: 60
  lookback_candles: 300
  atr_period: 14
  atr_mult_sl: 1.5
  fibo:
    use: true
    piv_window: 5
    anchors_to_consider: 3
  avwap:
    use: true
  min_tp_net_pct: 2.0
  fees:
    taker_pct: 0.06
    maker_pct: 0.02
    assume_maker: false
  slippage_pct: 0.02

risk:
  mode: "Balanced"
  risk_pct_by_mode:
    Conservative: 0.25
    Balanced: 0.5
    Aggressive: 1.0
  max_leverage: 10
  liquidation_buffer: 1.3
