app:
  data_dir: "data"
  db_path: "data/ohlcv.db"
  timezone: "UTC"

exchange:
  id: "bitget"
  rate_limit_ms: 350

symbols:
  - "BTC/USDT:USDT"
  - "ETH/USDT:USDT"
  - "SOL/USDT:USDT"
  - "XRP/USDT:USDT"
  - "DOGE/USDT:USDT"
  - "ADA/USDT:USDT"
  - "AVAX/USDT:USDT"
  - "LINK/USDT:USDT"
  - "TON/USDT:USDT"
  - "PEPE/USDT:USDT"

timeframes:
  - "1m"
  - "5m"
  - "15m"
  - "1h"

data:
  base_timeframe: "1m"
  derived_timeframes: ["5m", "15m", "1h"]
  resample:
    run_seconds: 60
    lookback_minutes: 720

backfill:
  start_date: "2020-01-01"
  start_days_ago: 365
  batch_limit: 1000

incremental:
  overlap_candles: 1
  run_seconds: 60

signals:
  scan_seconds: 60
  lookback_candles: 300
  atr_period: 14
  atr_mult_sl: 1.5
  fibo:
    use: true
    piv_window: 5
    anchors_to_consider: 3
  avwap:
    use: true
  min_tp_net_pct: 2.0
  fees:
    taker_pct: 0.06
    maker_pct: 0.02
    assume_maker: false
  slippage_pct: 0.02
  validity_candles: 60
  bar_policy: "conservative"   # TP i SL w tej samej świecy => SL

  evaluation:
    usd_per_trade: 100

execution:
  tp1_fraction: 0.5            # jaka część pozycji wychodzi na TP1
  move_sl_to_be_on_tp1: true   # po TP1 przenieś SL na BE (entry)
  trail:
    use: true
    method: "atr"              # "atr" (obsługiwane) / (w przyszłości: "swing")
    atr_period: 14
    atr_mult: 1.0              # np. 1.0 * ATR
